### PR TITLE
Fix chown for ZFS

### PR DESCRIPTION
**Pull request by einsibjarni**
We need to get the ZFS dataset mountpoint to pass to chown, we can't pass the dataset path.
This patch allows running the server as a normal user while using ZFS snapshots.
Tested on FreeBSD 12.2-RELEASE

### CODE REVIEW

**Comment by einsibjarni** [comment]
Any chance of getting this merged? It's needed to be able to run the server as regular user, and we're currently maintaining the patch locally and running with it for months

**Review by Johnnynator — CHANGES_REQUESTED** [review]
The indentation should be with tabs instead of spaces to keep consistency with the file.

**Comment by Johnnynator** [comment]
Otherwise would also like to see this merged. Patch also works fine with OpenZFS on Linux.

**Comment by nixcamic** [comment]
@uroni any chance we could get this merged into the 2.5.x branch also (unless 2.6 is forthcoming) so that ZFS features will work correctly on the next release?

**Comment by shampeon** [comment]
I'm trying to use urBackup in a Docker container in Open Media Vault with ZFS, and I'm hitting this bug.

**Comment by ragametal** [comment]
I'm also experiencing this bug in a Docker in Truenas Scale 24.10.2.

**Pull request merged**
