### PR TITLE
fix restore for filenames with single quotes

### PR DESCRIPTION
**Pull request by jcollonville**

### CODE REVIEW

**Comment by uroni** [comment]
Thx! The change that caused templates.js to change might be missing?

**Comment by jcollonville** [comment]
Hi, sorry I'm not sure to understand, the template.js changes are in this commit.

**Comment by uroni** [comment]
templates.js is generated from the files in `urbackupserver/www/templates`. So the next time I'd regenerate from those files your change would be lost.

**Comment by jcollonville** [comment]
Ok, fixed this as well. Thanks

**Comment by uroni** [comment]
Thanks!

**Pull request merged**
